// Virginia Home Essentials - Blog JavaScript

// Load blog posts from JSON file (generated by automation)
let blogPosts = [];

// Fetch blog posts from JSON
async function loadBlogPosts() {
    try {
        const response = await fetch('posts.json');
        if (response.ok) {
            const posts = await response.json();
            blogPosts = posts.map(post => ({
                id: post.id,
                title: post.title,
                slug: post.slug,
                excerpt: post.excerpt,
                category: post.category,
                categoryDisplay: formatCategory(post.category),
                image: post.featured_image || getDefaultImage(post.category),
                author: post.author,
                date: post.publish_date,
                readTime: post.read_time || "5 min read",
                featured: false  // Can be determined by logic
            }));
            console.log(`Loaded ${blogPosts.length} blog posts from database`);
            return blogPosts;
        } else {
            console.warn('Blog posts.json not found, using fallback data');
            return getFallbackPosts();
        }
    } catch (error) {
        console.warn('Error loading blog posts, using fallback:', error);
        return getFallbackPosts();
    }
}

function formatCategory(category) {
    return category.split('-').map(word => 
        word.charAt(0).toUpperCase() + word.slice(1)
    ).join(' ');
}

function getDefaultImage(category) {
    const images = {
        'smart-home': 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        'market-insights': 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        'product-guides': 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
        'home-maintenance': 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80'
    };
    return images[category] || images['market-insights'];
}

// Fallback data if JSON not available
function getFallbackPosts() {
    return [
    {
        id: 1,
        title: "10 Smart Home Essentials Every New Virginia Homeowner Needs",
        slug: "smart-home-essentials-virginia-homeowners",
        excerpt: "Transform your new home into a smart home with these must-have devices that enhance security, comfort, and energy efficiency for Virginia's unique climate.",
        category: "smart-home",
        categoryDisplay: "Smart Home",
        image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        author: "Virginia Home Essentials Team",
        date: "2025-12-08",
        readTime: "5 min read",
        featured: false
    },
    {
        id: 2,
        title: "Virginia Housing Market Update: Buyer's Market Emerges",
        slug: "virginia-housing-market-update-buyers-market",
        excerpt: "With inventory up 18% year-over-year and more favorable conditions for buyers, here's what new homeowners need to know about Virginia's evolving market.",
        category: "market-insights",
        categoryDisplay: "Market Insights",
        image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        author: "Market Analysis Team",
        date: "2025-12-07",
        readTime: "7 min read",
        featured: true
    },
    {
        id: 3,
        title: "First-Time Home Buyer's Kitchen Setup Guide",
        slug: "first-time-buyer-kitchen-setup-guide",
        excerpt: "Essential kitchen appliances and tools that every new homeowner should have, from basic cookware to smart appliances that make cooking easier.",
        category: "product-guides",
        categoryDisplay: "Product Guides",
        image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        author: "Product Review Team",
        date: "2025-12-06",
        readTime: "6 min read",
        featured: false
    },
    {
        id: 4,
        title: "Winter Home Maintenance Checklist for Virginia",
        slug: "winter-home-maintenance-checklist-virginia",
        excerpt: "Prepare your Virginia home for winter with this comprehensive maintenance checklist covering HVAC, plumbing, and weatherproofing essentials.",
        category: "home-maintenance",
        categoryDisplay: "Home Maintenance",
        image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        author: "Home Care Experts",
        date: "2025-12-05",
        readTime: "8 min read",
        featured: false
    },
    {
        id: 5,
        title: "Best Home Security Systems for Virginia Homeowners",
        slug: "best-home-security-systems-virginia",
        excerpt: "Compare top-rated home security systems perfect for Virginia homes, including wireless options, smart features, and professional monitoring services.",
        category: "product-guides",
        categoryDisplay: "Product Guides",
        image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        author: "Security Specialists",
        date: "2025-12-04",
        readTime: "9 min read",
        featured: false
    },
    {
        id: 6,
        title: "Virginia First-Time Buyer Programs: Complete Guide 2025",
        slug: "virginia-first-time-buyer-programs-2025",
        excerpt: "Discover all available first-time homebuyer programs in Virginia, including VHDA loans, down payment assistance, and qualification requirements.",
        category: "first-time-buyers",
        categoryDisplay: "First-Time Buyers",
        image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        author: "Real Estate Advisors",
        date: "2025-12-03",
        readTime: "10 min read",
        featured: false
    },
    {
        id: 7,
        title: "Energy-Efficient Appliances for Virginia's Climate",
        slug: "energy-efficient-appliances-virginia-climate",
        excerpt: "Save money on utility bills with these energy-efficient appliances specifically chosen for Virginia's humid subtropical climate and seasonal variations.",
        category: "product-guides",
        categoryDisplay: "Product Guides",
        image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        author: "Energy Efficiency Team",
        date: "2025-12-02",
        readTime: "7 min read",
        featured: false
    },
    {
        id: 8,
        title: "Spring Home Preparation: Virginia Homeowner's Guide",
        slug: "spring-home-preparation-virginia-guide",
        excerpt: "Get your Virginia home ready for spring with this comprehensive guide covering HVAC maintenance, outdoor prep, and seasonal cleaning tasks.",
        category: "seasonal",
        categoryDisplay: "Seasonal Tips",
        image: "https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        author: "Seasonal Care Team",
        date: "2025-12-01",
        readTime: "6 min read",
        featured: false
    },
    {
        id: 9,
        title: "Smart Thermostat Installation: DIY vs Professional",
        slug: "smart-thermostat-installation-diy-vs-professional",
        excerpt: "Should you install a smart thermostat yourself or hire a professional? We break down the pros, cons, and costs for Virginia homeowners.",
        category: "smart-home",
        categoryDisplay: "Smart Home",
        image: "https://images.unsplash.com/photo-1545259741-2ea3ebf61fa0?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        author: "DIY Experts",
        date: "2025-11-30",
        readTime: "5 min read",
        featured: false
    },
    {
        id: 10,
        title: "Northern Virginia vs Richmond: Market Comparison",
        slug: "northern-virginia-vs-richmond-market-comparison",
        excerpt: "Comparing home prices, market trends, and buyer opportunities between Northern Virginia and Richmond metro areas for first-time buyers.",
        category: "market-insights",
        categoryDisplay: "Market Insights",
        image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        author: "Regional Market Team",
        date: "2025-11-29",
        readTime: "8 min read",
        featured: false
    },
    {
        id: 11,
        title: "Essential Tools Every New Homeowner Should Own",
        slug: "essential-tools-new-homeowner-should-own",
        excerpt: "Build your first tool collection with these essential items every Virginia homeowner needs for basic maintenance and DIY projects.",
        category: "home-maintenance",
        categoryDisplay: "Home Maintenance",
        image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        author: "Tool Specialists",
        date: "2025-11-28",
        readTime: "6 min read",
        featured: false
    },
    {
        id: 12,
        title: "Holiday Decorating on a New Homeowner Budget",
        slug: "holiday-decorating-new-homeowner-budget",
        excerpt: "Create beautiful holiday decorations for your new Virginia home without breaking the bank. Budget-friendly tips and DIY ideas included.",
        category: "seasonal",
        categoryDisplay: "Seasonal Tips",
        image: "https://images.unsplash.com/photo-1512389142860-9c449e58a543?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        author: "Decor Team",
        date: "2025-11-27",
        readTime: "5 min read",
    }
    ];
}

// DOM Elements
const postsContainer = document.getElementById('posts-container');
const filterButtons = document.querySelectorAll('.filter-btn');
const categoryCards = document.querySelectorAll('.category-card');
const loadMoreBtn = document.getElementById('load-more-btn');
const newsletterForm = document.querySelector('.newsletter-form');

// State
let currentFilter = 'all';
let postsPerPage = 6;
let currentPage = 1;
let filteredPosts = [];

// Initialize blog - load posts from JSON first
document.addEventListener('DOMContentLoaded', async function() {
    blogPosts = await loadBlogPosts();
    filteredPosts = [...blogPosts];
    loadPosts();
    setupEventListeners();
    updateCategoryCounts();
});

// Load and display posts
function loadPosts(append = false) {
    if (!postsContainer) return;
    
    // Filter posts based on current filter
    if (currentFilter === 'all') {
        filteredPosts = [...blogPosts];
    } else {
        filteredPosts = blogPosts.filter(post => post.category === currentFilter);
    }
    
    // Calculate posts to show
    const startIndex = append ? (currentPage - 1) * postsPerPage : 0;
    const endIndex = currentPage * postsPerPage;
    const postsToShow = filteredPosts.slice(startIndex, endIndex);
    
    // Clear container if not appending
    if (!append) {
        postsContainer.innerHTML = '';
    }
    
    // Show loading if no posts yet
    if (postsToShow.length === 0 && !append) {
        postsContainer.innerHTML = '<div class="loading-posts"><div class="spinner"></div></div>';
        return;
    }
    
    // Create post cards
    postsToShow.forEach((post, index) => {
        const postCard = createPostCard(post, startIndex + index);
        postsContainer.appendChild(postCard);
    });
    
    // Update load more button
    updateLoadMoreButton();
    
    // Remove loading spinner
    const loadingElement = document.querySelector('.loading-posts');
    if (loadingElement) {
        loadingElement.remove();
    }
}

// Create individual post card
function createPostCard(post, index) {
    const card = document.createElement('div');
    card.className = 'post-card';
    card.style.animationDelay = `${(index % 6) * 0.1}s`;
    
    const formattedDate = formatDate(post.date);
    
    card.innerHTML = `
        <div class="post-image">
            <img src="${post.image}" alt="${post.title}" loading="lazy">
            <div class="post-category-badge">${post.categoryDisplay}</div>
        </div>
        <div class="post-content">
            <div class="post-meta">
                <span><i class="fas fa-calendar"></i> ${formattedDate}</span>
                <span><i class="fas fa-clock"></i> ${post.readTime}</span>
                <span><i class="fas fa-user"></i> ${post.author}</span>
            </div>
            <h3 class="post-title">
                <a href="${post.slug}.html">${post.title}</a>
            </h3>
            <p class="post-excerpt">${post.excerpt}</p>
            <div class="post-footer">
                <div class="author-info">
                    <i class="fas fa-user-circle"></i>
                    <span>${post.author}</span>
                </div>
                <a href="${post.slug}.html" class="read-more">
                    Read More <i class="fas fa-arrow-right"></i>
                </a>
            </div>
        </div>
    `;
    
    return card;
}

// Format date for display
function formatDate(dateString) {
    const date = new Date(dateString);
    const options = { year: 'numeric', month: 'long', day: 'numeric' };
    return date.toLocaleDateString('en-US', options);
}

// Setup event listeners
function setupEventListeners() {
    // Filter buttons
    filterButtons.forEach(button => {
        button.addEventListener('click', function() {
            const filter = this.dataset.filter;
            
            // Update active button
            filterButtons.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');
            
            // Update filter and reload posts
            currentFilter = filter;
            currentPage = 1;
            loadPosts();
            
            // Track filter usage
            trackEvent('blog_filter_used', {
                filter: filter,
                timestamp: new Date().toISOString()
            });
        });
    });
    
    // Category cards
    categoryCards.forEach(card => {
        card.addEventListener('click', function() {
            const category = this.dataset.category;
            
            // Update filter buttons
            filterButtons.forEach(btn => btn.classList.remove('active'));
            const targetButton = document.querySelector(`[data-filter="${category}"]`);
            if (targetButton) {
                targetButton.classList.add('active');
            }
            
            // Update filter and reload posts
            currentFilter = category;
            currentPage = 1;
            loadPosts();
            
            // Scroll to posts section
            document.querySelector('.latest-posts').scrollIntoView({
                behavior: 'smooth'
            });
            
            // Track category selection
            trackEvent('blog_category_selected', {
                category: category,
                timestamp: new Date().toISOString()
            });
        });
    });
    
    // Load more button
    if (loadMoreBtn) {
        loadMoreBtn.addEventListener('click', function() {
            currentPage++;
            loadPosts(true);
            
            // Track load more usage
            trackEvent('blog_load_more', {
                page: currentPage,
                filter: currentFilter,
                timestamp: new Date().toISOString()
            });
        });
    }
    
    // Newsletter form
    if (newsletterForm) {
        newsletterForm.addEventListener('submit', function(e) {
            e.preventDefault();
            
            const email = this.querySelector('input[type="email"]').value;
            
            // Here you would typically send the email to your backend
            // For now, we'll show a success message
            showNotification('Thank you for subscribing! You\'ll receive our weekly newsletter with the latest Virginia real estate insights and home essentials.', 'success');
            
            // Track newsletter signup
            trackEvent('newsletter_signup', {
                email: email,
                source: 'blog_page',
                timestamp: new Date().toISOString()
            });
            
            this.reset();
        });
    }
    
    // Mobile menu (inherited from main site)
    const hamburger = document.querySelector('.hamburger');
    const navMenu = document.querySelector('.nav-menu');
    
    if (hamburger && navMenu) {
        hamburger.addEventListener('click', function() {
            navMenu.classList.toggle('active');
        });
    }
}

// Update load more button visibility
function updateLoadMoreButton() {
    if (!loadMoreBtn) return;
    
    const totalShown = currentPage * postsPerPage;
    const hasMore = totalShown < filteredPosts.length;
    
    if (hasMore) {
        loadMoreBtn.style.display = 'inline-block';
        loadMoreBtn.textContent = `Load More Articles (${filteredPosts.length - totalShown} remaining)`;
    } else {
        loadMoreBtn.style.display = 'none';
    }
}

// Update category counts
function updateCategoryCounts() {
    const categoryCounts = {};
    
    // Count posts by category
    blogPosts.forEach(post => {
        categoryCounts[post.category] = (categoryCounts[post.category] || 0) + 1;
    });
    
    // Update category cards
    categoryCards.forEach(card => {
        const category = card.dataset.category;
        const countElement = card.querySelector('.post-count');
        if (countElement && categoryCounts[category]) {
            const count = categoryCounts[category];
            countElement.textContent = `${count} article${count !== 1 ? 's' : ''}`;
        }
    });
}

// Show notification
function showNotification(message, type = 'info') {
    // Create notification element
    const notification = document.createElement('div');
    notification.className = `notification notification-${type}`;
    notification.innerHTML = `
        <div class="notification-content">
            <i class="fas fa-${type === 'success' ? 'check-circle' : 'info-circle'}"></i>
            <span>${message}</span>
            <button class="notification-close">
                <i class="fas fa-times"></i>
            </button>
        </div>
    `;
    
    // Add styles
    notification.style.cssText = `
        position: fixed;
        top: 20px;
        right: 20px;
        background: ${type === 'success' ? '#10b981' : '#2563eb'};
        color: white;
        padding: 0;
        border-radius: 8px;
        box-shadow: 0 10px 25px rgba(0,0,0,0.1);
        z-index: 10000;
        max-width: 400px;
        animation: slideInRight 0.3s ease;
    `;
    
    // Add to page
    document.body.appendChild(notification);
    
    // Auto remove after 5 seconds
    setTimeout(() => {
        if (notification.parentNode) {
            notification.style.animation = 'slideOutRight 0.3s ease';
            setTimeout(() => {
                if (notification.parentNode) {
                    notification.remove();
                }
            }, 300);
        }
    }, 5000);
    
    // Close button
    const closeBtn = notification.querySelector('.notification-close');
    closeBtn.addEventListener('click', () => {
        notification.style.animation = 'slideOutRight 0.3s ease';
        setTimeout(() => {
            if (notification.parentNode) {
                notification.remove();
            }
        }, 300);
    });
}

// Track events (same as main site)
function trackEvent(eventName, eventData) {
    // Store events in localStorage for now
    // In production, you'd send this to your analytics service
    const events = JSON.parse(localStorage.getItem('blog_events') || '[]');
    events.push({
        event: eventName,
        data: eventData
    });
    localStorage.setItem('blog_events', JSON.stringify(events));
    
    console.log('Blog event tracked:', eventName, eventData);
}

// Search functionality (for future implementation)
function searchPosts(query) {
    const searchResults = blogPosts.filter(post => 
        post.title.toLowerCase().includes(query.toLowerCase()) ||
        post.excerpt.toLowerCase().includes(query.toLowerCase()) ||
        post.categoryDisplay.toLowerCase().includes(query.toLowerCase())
    );
    
    return searchResults;
}

// Related posts functionality
function getRelatedPosts(currentPost, limit = 3) {
    const related = blogPosts
        .filter(post => post.id !== currentPost.id && post.category === currentPost.category)
        .slice(0, limit);
    
    // If not enough related posts in same category, fill with other posts
    if (related.length < limit) {
        const additional = blogPosts
            .filter(post => post.id !== currentPost.id && !related.includes(post))
            .slice(0, limit - related.length);
        
        related.push(...additional);
    }
    
    return related;
}

// Add CSS animations
const style = document.createElement('style');
style.textContent = `
    @keyframes slideInRight {
        from {
            transform: translateX(100%);
            opacity: 0;
        }
        to {
            transform: translateX(0);
            opacity: 1;
        }
    }
    
    @keyframes slideOutRight {
        from {
            transform: translateX(0);
            opacity: 1;
        }
        to {
            transform: translateX(100%);
            opacity: 0;
        }
    }
    
    .notification-content {
        display: flex;
        align-items: center;
        gap: 0.75rem;
    }
    
    .notification-close {
        background: none;
        border: none;
        color: white;
        cursor: pointer;
        padding: 0;
        margin-left: auto;
    }
    
    .notification-close:hover {
        opacity: 0.8;
    }
`;
document.head.appendChild(style);

// Export functions for potential use in other scripts
window.BlogSystem = {
    loadPosts,
    searchPosts,
    getRelatedPosts,
    trackEvent,
    blogPosts
};

